/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportesRouteImport } from './routes/_app/reportes'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCxcRouteImport } from './routes/_app/cxc'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AppVentasNuevaRouteImport } from './routes/_app/ventas/nueva'
import { Route as AppVentasNotasCreditoRouteImport } from './routes/_app/ventas/notas-credito'
import { Route as AppInventarioRecetasRouteImport } from './routes/_app/inventario/recetas'
import { Route as AppInventarioProductosRouteImport } from './routes/_app/inventario/productos'
import { Route as AppInventarioKardexRouteImport } from './routes/_app/inventario/kardex'
import { Route as AppInventarioDepartamentosRouteImport } from './routes/_app/inventario/departamentos'
import { Route as AppConfiguracionTasaCambioRouteImport } from './routes/_app/configuracion/tasa-cambio'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportesRoute = AppReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCxcRoute = AppCxcRouteImport.update({
  id: '/cxc',
  path: '/cxc',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const AppVentasNuevaRoute = AppVentasNuevaRouteImport.update({
  id: '/ventas/nueva',
  path: '/ventas/nueva',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVentasNotasCreditoRoute = AppVentasNotasCreditoRouteImport.update({
  id: '/ventas/notas-credito',
  path: '/ventas/notas-credito',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioRecetasRoute = AppInventarioRecetasRouteImport.update({
  id: '/inventario/recetas',
  path: '/inventario/recetas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioProductosRoute = AppInventarioProductosRouteImport.update({
  id: '/inventario/productos',
  path: '/inventario/productos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioKardexRoute = AppInventarioKardexRouteImport.update({
  id: '/inventario/kardex',
  path: '/inventario/kardex',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventarioDepartamentosRoute =
  AppInventarioDepartamentosRouteImport.update({
    id: '/inventario/departamentos',
    path: '/inventario/departamentos',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConfiguracionTasaCambioRoute =
  AppConfiguracionTasaCambioRouteImport.update({
    id: '/configuracion/tasa-cambio',
    path: '/configuracion/tasa-cambio',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/clientes': typeof AppClientesRoute
  '/cxc': typeof AppCxcRoute
  '/dashboard': typeof AppDashboardRoute
  '/reportes': typeof AppReportesRoute
  '/configuracion/tasa-cambio': typeof AppConfiguracionTasaCambioRoute
  '/inventario/departamentos': typeof AppInventarioDepartamentosRoute
  '/inventario/kardex': typeof AppInventarioKardexRoute
  '/inventario/productos': typeof AppInventarioProductosRoute
  '/inventario/recetas': typeof AppInventarioRecetasRoute
  '/ventas/notas-credito': typeof AppVentasNotasCreditoRoute
  '/ventas/nueva': typeof AppVentasNuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/clientes': typeof AppClientesRoute
  '/cxc': typeof AppCxcRoute
  '/dashboard': typeof AppDashboardRoute
  '/reportes': typeof AppReportesRoute
  '/configuracion/tasa-cambio': typeof AppConfiguracionTasaCambioRoute
  '/inventario/departamentos': typeof AppInventarioDepartamentosRoute
  '/inventario/kardex': typeof AppInventarioKardexRoute
  '/inventario/productos': typeof AppInventarioProductosRoute
  '/inventario/recetas': typeof AppInventarioRecetasRoute
  '/ventas/notas-credito': typeof AppVentasNotasCreditoRoute
  '/ventas/nueva': typeof AppVentasNuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/cxc': typeof AppCxcRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/reportes': typeof AppReportesRoute
  '/_app/configuracion/tasa-cambio': typeof AppConfiguracionTasaCambioRoute
  '/_app/inventario/departamentos': typeof AppInventarioDepartamentosRoute
  '/_app/inventario/kardex': typeof AppInventarioKardexRoute
  '/_app/inventario/productos': typeof AppInventarioProductosRoute
  '/_app/inventario/recetas': typeof AppInventarioRecetasRoute
  '/_app/ventas/notas-credito': typeof AppVentasNotasCreditoRoute
  '/_app/ventas/nueva': typeof AppVentasNuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/clientes'
    | '/cxc'
    | '/dashboard'
    | '/reportes'
    | '/configuracion/tasa-cambio'
    | '/inventario/departamentos'
    | '/inventario/kardex'
    | '/inventario/productos'
    | '/inventario/recetas'
    | '/ventas/notas-credito'
    | '/ventas/nueva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/clientes'
    | '/cxc'
    | '/dashboard'
    | '/reportes'
    | '/configuracion/tasa-cambio'
    | '/inventario/departamentos'
    | '/inventario/kardex'
    | '/inventario/productos'
    | '/inventario/recetas'
    | '/ventas/notas-credito'
    | '/ventas/nueva'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_app'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_app/clientes'
    | '/_app/cxc'
    | '/_app/dashboard'
    | '/_app/reportes'
    | '/_app/configuracion/tasa-cambio'
    | '/_app/inventario/departamentos'
    | '/_app/inventario/kardex'
    | '/_app/inventario/productos'
    | '/_app/inventario/recetas'
    | '/_app/ventas/notas-credito'
    | '/_app/ventas/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reportes': {
      id: '/_app/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AppReportesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cxc': {
      id: '/_app/cxc'
      path: '/cxc'
      fullPath: '/cxc'
      preLoaderRoute: typeof AppCxcRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_app/ventas/nueva': {
      id: '/_app/ventas/nueva'
      path: '/ventas/nueva'
      fullPath: '/ventas/nueva'
      preLoaderRoute: typeof AppVentasNuevaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ventas/notas-credito': {
      id: '/_app/ventas/notas-credito'
      path: '/ventas/notas-credito'
      fullPath: '/ventas/notas-credito'
      preLoaderRoute: typeof AppVentasNotasCreditoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/recetas': {
      id: '/_app/inventario/recetas'
      path: '/inventario/recetas'
      fullPath: '/inventario/recetas'
      preLoaderRoute: typeof AppInventarioRecetasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/productos': {
      id: '/_app/inventario/productos'
      path: '/inventario/productos'
      fullPath: '/inventario/productos'
      preLoaderRoute: typeof AppInventarioProductosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/kardex': {
      id: '/_app/inventario/kardex'
      path: '/inventario/kardex'
      fullPath: '/inventario/kardex'
      preLoaderRoute: typeof AppInventarioKardexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventario/departamentos': {
      id: '/_app/inventario/departamentos'
      path: '/inventario/departamentos'
      fullPath: '/inventario/departamentos'
      preLoaderRoute: typeof AppInventarioDepartamentosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion/tasa-cambio': {
      id: '/_app/configuracion/tasa-cambio'
      path: '/configuracion/tasa-cambio'
      fullPath: '/configuracion/tasa-cambio'
      preLoaderRoute: typeof AppConfiguracionTasaCambioRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppCxcRoute: typeof AppCxcRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppReportesRoute: typeof AppReportesRoute
  AppConfiguracionTasaCambioRoute: typeof AppConfiguracionTasaCambioRoute
  AppInventarioDepartamentosRoute: typeof AppInventarioDepartamentosRoute
  AppInventarioKardexRoute: typeof AppInventarioKardexRoute
  AppInventarioProductosRoute: typeof AppInventarioProductosRoute
  AppInventarioRecetasRoute: typeof AppInventarioRecetasRoute
  AppVentasNotasCreditoRoute: typeof AppVentasNotasCreditoRoute
  AppVentasNuevaRoute: typeof AppVentasNuevaRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppCxcRoute: AppCxcRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppReportesRoute: AppReportesRoute,
  AppConfiguracionTasaCambioRoute: AppConfiguracionTasaCambioRoute,
  AppInventarioDepartamentosRoute: AppInventarioDepartamentosRoute,
  AppInventarioKardexRoute: AppInventarioKardexRoute,
  AppInventarioProductosRoute: AppInventarioProductosRoute,
  AppInventarioRecetasRoute: AppInventarioRecetasRoute,
  AppVentasNotasCreditoRoute: AppVentasNotasCreditoRoute,
  AppVentasNuevaRoute: AppVentasNuevaRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
